
namespace Elements
{
    public class UnicodeCategories
    {
        public static string[] UnicodeName;

        public static string[] UnicodeAbbrev;

        static UnicodeCategories()
        {
            string[] strArrays = new string[] { "All Control Characters", "All Letters", "All Diacritical Marks", "All Numbers", "All Punctuation", "All Symbols", "All Separators", "Closing Punctuation", "Connector Punctuation", "Control Code", "Currency Symbol", "Dash Punctuation", "Decimal Digit Number", "Enclosing Mark", "Final Quote Punctuation", "Format", "Initial Quote Punctuation", "Letter Number", "Line Separator", "Lowercase Letter", "Math Symbol", "Modifier Letter", "Modifier Symbol", "Nonspacing Mark", "Open Punctuation", "Other Letter", "Other Not Assigned", "Other Number", "Other Punctuation", "Other Symbol", "Paragraph Separator", "Private Use", "Space Separator", "Space Combining Mark", "Surrogate", "Titlecase Letter", "Uppercase Letter", "Alphabetic Presentation Forms", "Arabic", "Arabic Presentation Forms-A", "Arabic Presentation Forms-B", "Armenian", "Arrows", "Basic Latin", "Bengali", "Block Elements", "Bopomofo", "Bopomofo Extended", "Box Drawing", "Braille Patterns", "Buhid", "CJK Compatibility", "CJK Compatibility Forms", "CJK Compatibility Ideographs", "CJK Radicals Supplement", "CJK Symbolsand Punctuation", "CJK Unified Ideographs", "CJK Unified Ideographs Extension A", "Cherokee", "Combining Diacritical Marks", "Combining Diacritical Marks for Symbols", "Combining Half Marks", "Combining Marks for Symbols", "Control Pictures", "Currency Symbols", "Cyrillic", "Cyrillic Supplement", "Devanagari", "Dingbats", "Enclosed Alphanumerics", "Enclosed CJK Letters and Months", "Ethiopic", "General Punctuation", "Geometric Shapes", "Georgian", "Greek", "Greek Extended", "Greek and Coptic", "Gujarati", "Gurmukhi", "Halfwidth and Fullwidth Forms", "Hangul Compatibility Jamo", "Hangul Jamo", "Hangul Syllables", "Hanunoo", "Hebrew", "High Private Use Surrogates", "High Surrogates", "Hiragana", "IPA Extensions", "Ideographic Description Characters", "Kanbun", "Kangxi Radicals", "Kannada", "Katakana", "Katakana Phonetic Extensions", "Khmer", "Khmer Symbols", "Lao", "Latin-1 Supplement", "Latin Extended-A", "Latin Extended-B", "Latin Extended Additional", "Letterlike Symbols", "Limbu", "Low Surrogates", "Malayalam", "Mathematical Operators", "Miscellaneous Mathematical Symbols-A", "Miscellaneous Mathematical Symbols-B", "Miscellaneous Symbols", "Miscellaneous Symbols and Arrows", "Miscellaneous Technical", "Mongolian", "Myanmar", "Number Forms", "Ogham", "Optical Character Recognition", "Oriya", "Phonetic Extensions", "Private Use", "Private Use Area", "Runic", "Sinhala", "Small Form Variants", "Spacing Modifier Letters", "Specials", "Superscripts and Subscripts", "Supplemental Arrows-A", "Supplemental Arrows-B", "Supplemental Mathematical Operators", "Syriac", "Tagalog", "Tagbanwa", "Tai Le", "Tamil", "Telugu", "Thaana", "Thai", "Tibetan", "Unified Canadian Aboriginal Syllabics", "Variation Selectors", "Yi Radicals", "Yi Syllables", "Yijing Hexagram Symbols" };
            UnicodeCategories.UnicodeName = strArrays;
            string[] strArrays1 = new string[] { "C", "L", "M", "N", "P", "S", "Z", "Pe", "Pc", "Cc", "Sc", "Pd", "Nd", "Me", "Pf", "Cf", "Pi", "Nl", "Zl", "Ll", "Sm", "Lm", "Sk", "Mn", "Ps", "Lo", "Cn", "No", "Po", "So", "Zp", "Co", "Zs", "Mc", "Cs", "Lt", "Lu", "IsAlphabeticPresentationForms", "IsArabic", "IsArabicPresentationForms-A", "IsArabicPresentationForms-B", "IsArmenian", "IsArrows", "IsBasicLatin", "IsBengali", "IsBlockElements", "IsBopomofo", "IsBopomofoExtended", "IsBoxDrawing", "IsBraillePatterns", "IsBuhid", "IsCJKCompatibility", "IsCJKCompatibilityForms", "IsCJKCompatibilityIdeographs", "IsCJKRadicalsSupplement", "IsCJKSymbolsandPunctuation", "IsCJKUnifiedIdeographs", "IsCJKUnifiedIdeographsExtensionA", "IsCherokee", "IsCombiningDiacriticalMarks", "IsCombiningDiacriticalMarksforSymbols", "IsCombiningHalfMarks", "IsCombiningMarksforSymbols", "IsControlPictures", "IsCurrencySymbols", "IsCyrillic", "IsCyrillicSupplement", "IsDevanagari", "IsDingbats", "IsEnclosedAlphanumerics", "IsEnclosedCJKLettersandMonths", "IsEthiopic", "IsGeneralPunctuation", "IsGeometricShapes", "IsGeorgian", "IsGreek", "IsGreekExtended", "IsGreekandCoptic", "IsGujarati", "IsGurmukhi", "IsHalfwidthandFullwidthForms", "IsHangulCompatibilityJamo", "IsHangulJamo", "IsHangulSyllables", "IsHanunoo", "IsHebrew", "IsHighPrivateUseSurrogates", "IsHighSurrogates", "IsHiragana", "IsIPAExtensions", "IsIdeographicDescriptionCharacters", "IsKanbun", "IsKangxiRadicals", "IsKannada", "IsKatakana", "IsKatakanaPhoneticExtensions", "IsKhmer", "IsKhmerSymbols", "IsLao", "IsLatin-1Supplement", "IsLatinExtended-A", "IsLatinExtended-B", "IsLatinExtendedAdditional", "IsLetterlikeSymbols", "IsLimbu", "IsLowSurrogates", "IsMalayalam", "IsMathematicalOperators", "IsMiscellaneousMathematicalSymbols-A", "IsMiscellaneousMathematicalSymbols-B", "IsMiscellaneousSymbols", "IsMiscellaneousSymbolsandArrows", "IsMiscellaneousTechnical", "IsMongolian", "IsMyanmar", "IsNumberForms", "IsOgham", "IsOpticalCharacterRecognition", "IsOriya", "IsPhoneticExtensions", "IsPrivateUse", "IsPrivateUseArea", "IsRunic", "IsSinhala", "IsSmallFormVariants", "IsSpacingModifierLetters", "IsSpecials", "IsSuperscriptsandSubscripts", "IsSupplementalArrows-A", "IsSupplementalArrows-B", "IsSupplementalMathematicalOperators", "IsSyriac", "IsTagalog", "IsTagbanwa", "IsTaiLe", "IsTamil", "IsTelugu", "IsThaana", "IsThai", "IsTibetan", "IsUnifiedCanadianAboriginalSyllabics", "IsVariationSelectors", "IsYiRadicals", "IsYiSyllables", "IsYijingHexagramSymbols" };
            UnicodeCategories.UnicodeAbbrev = strArrays1;
        }
    }
}